//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vouchers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int idVoucher { get; set; }
        public Nullable<int> idTour { get; set; }
        public string voucherName { get; set; }
        public string descr { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> numberOfPeople { get; set; }
        public Nullable<bool> nutrition { get; set; }
        public Nullable<bool> accommodation { get; set; }
        public Nullable<bool> hot { get; set; }
        public Nullable<int> discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Tours Tours { get; set; }
    }
}
